# mdBook configuration file

[book]
title = "The Official Radare2 Book"
author = "pancake <pancake@nopcode.org>"
description = "The Official Radare2 Book"
language = "en"

[build]
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/radareorg/radare2-book"
edit-url-template = "https://github.com/radareorg/radare2-book/edit/master/src/{path}"
site-url = "/"

[output.html.search]
limit-results = 15
